exclude: |
  (?x)^(
    .editorconfig|
    .devcontainer/devcontainer.json|
    Directory.Packages.props
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-xml
  - id: check-yaml
    args: [--allow-multiple-documents]
  #- id: check-json #Note: now we are using check-json5
  - id: check-added-large-files
    args: [--maxkb=50]
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: double-quote-string-fixer
- repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
  hooks:
  - id: check-json5
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.45.0
  hooks:
  - id: markdownlint
    args: ["--disable", "MD013", "--disable", "MD034", "--"]
