parameters:
- name: BuildConfiguration
  displayName: Select BuildConfiguration
  type: string
  default: release
  values:
  - release
  - debug

trigger:
  batch: true
  branches:
    include:
    - master
    - hotfix/*
    - feature/*
  paths:
    exclude:
    - .azure-pipelines
    - LICENSE
    - README.md

resources:
  repositories:
  - repository: sharedTemplates
    type: github
    name: f2calv/CasCap.YAMLTemplates
    endpoint: github.com_f2calv

variables:
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - group: nuget-prod
- ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - group: nuget-dev

pool:
  vmImage: ubuntu-latest

extends:
  template: pipelines/dotnet-publish-nuget-v1.yml@sharedTemplates
  parameters:
    BuildConfiguration: ${{ parameters.BuildConfiguration }}
    CoverageInclude: '[CasCap.*]*'
    gitHubConnection: github.com_f2calv